#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  🔧 Screen Recording Permission Fix for Chrome Titles          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📊 DIAGNOSIS:"
echo "  - AppleScript CAN get Chrome titles ✅"
echo "  - active-win CANNOT get Chrome titles ❌"
echo "  - This means Screen Recording permission needs to be reset"
echo ""

echo "🎯 ROOT CAUSE:"
echo "  The 'active-win' library uses native macOS APIs that require"
echo "  Screen Recording permission to access window titles for some apps"
echo "  (especially browsers like Chrome)."
echo ""
echo "  Even though Terminal.app may appear in Screen Recording settings,"
echo "  the permission may not be properly granted or needs to be reset."
echo ""

echo "🔧 SOLUTION:"
echo ""
echo "  Step 1: Open System Settings"
echo "    - Click the Apple menu () → System Settings"
echo ""
echo "  Step 2: Go to Privacy & Security"
echo "    - Click 'Privacy & Security' in the sidebar"
echo ""
echo "  Step 3: Click 'Screen Recording'"
echo "    - Scroll down and click 'Screen Recording'"
echo ""
echo "  Step 4: Find Terminal"
echo "    - Look for 'Terminal' in the list"
echo "    - If it's there with a checkmark, UNCHECK it, then CHECK it again"
echo "    - If it's NOT there, click the '+' button and add:"
echo "      /System/Applications/Utilities/Terminal.app"
echo ""
echo "  Step 5: Restart Terminal"
echo "    - Quit Terminal completely (Cmd+Q)"
echo "    - Reopen Terminal"
echo "    - Navigate back to this directory"
echo ""
echo "  Step 6: Restart the tracker"
echo "    - Run: ./start-tui.sh"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""

read -p "Press Enter to open System Settings to Screen Recording... " 

# Open System Settings to Privacy & Security
open "x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture"

echo ""
echo "✅ System Settings opened!"
echo ""
echo "Follow the steps above, then:"
echo "  1. Quit Terminal (Cmd+Q)"
echo "  2. Reopen Terminal"
echo "  3. cd to this directory"
echo "  4. Run: ./scripts/verify-chrome-titles.sh"
echo ""

